### ISSUE TITLE
Sao Tome has noculture pops

### ISSUE THREAD

**Issue by Lys0gen** [Pergame35/Divergences#106]
Pops in province 1954 have the *castil**l**ian* culture, which should be spelled with just one L. 
Relevant file /history/pops/1836.1.1/Sao Tome.txt

**Comment by Lys0gen** [comment]
While at it: It's a bit weird that there are exactly 600 *circassian* pops (500 in Constantinople, 100 in Amman), which are not even accepted in *Circassia* (which has the *Caucasian Minor* culture).

**Comment by Capitanloco6** [comment]
Thanks for reporting, fixed! Also, thank you very much for all the fixes you commited throughout 2019-2020
