### ISSUE TITLE
Dismantling the Dual Monarchy as the HBE crashes the game

### ISSUE THREAD

**Issue by CharlesviBritannia** [Pergame35/Divergences#112]
I'm playing as the Holy Britannian Empire, and I can dismantle Scandinavia just fine. However, when I try to dismantle the DM, that crashes the game. I confirm this by tagging into the DM after the peace deal and manually firing their unique dismantling event (event 96041) myself. When hovering over the "We welcome peace" message, the game just shut down, no warning/report.
Edit: So the event to dismantle the DUA crashes the game for me no matter what. 1836 start date, execute event and it just crashes
Thank you for the awesome mod and for reading my issue

**Comment by Capitanloco6** [comment]
Fixed, thanks for reporting!
