### ISSUE TITLE
Event 22250 can not work correctly

### ISSUE THREAD

**Issue by shudorcl** [Pergame35/Divergences#114]
Hello ,when Dissolution of the Commonwealth happen,I found PLC is still PLC, but it should change into POL. May be it is because `change_tag_no_core_switch = POL` in event 22250 can not change PLC to POL. And I try to fix it.
```
change_tag = POL
any_country = {
	any_owned = {
		limit = { is_core = PLC }
                    remove_core = POL
			}
		}
```
It can work ,but still has some problem.
Finally, please forgive my low level English QAQ.

**Comment by Capitanloco6** [comment]
Thanks for reporting, fixed!
