### ISSUE TITLE
Some minor stuff that is wrong from the Original version

### ISSUE THREAD

**Issue by Mestrehunter** [Pergame35/Divergences#117]
- Lusitania(LST) Capital is Nova Lisboa(137) not Porto Novo(90)
- Crete(848,847) Turkish pops should be Venetians, the Turkish cores are also wrong. Since Crete always have been Venetian. 

Now some minor personal suggestions:

- Portuguese culture distribution is bad, the North (518,519,520) should be the one having most Portuguese pops, especially with Galicians been Portuguese, roughed terrain and it is the home of the portuguese nation. The South (525, 526, 527) which was less populated thanks to risk of invasion from Spain could be more populated in this TLN (since you know, Portugal formed Spain xD) and have a bigger Castilian population, especially Faro(527) which was isolated from the rest of Portugal.

**Comment by Capitanloco6** [comment]
Those are some very good suggestions, I'll implement them this weekend. Thanks!
