### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Andenfighter** [Pergame35/Divergences#134]
As Plantagenia, the game crashes for me two months into the game because of an event called "birth rate high". it makes it unplayable

**Comment by Andenfighter** [comment]
never mind, it's just that every event that fires crashes the game. i don't know what i did wrong

**Comment by Capitanloco6** [comment]
Are you playing with the latest version of the mod? I don't think these birth rate events exist anymore in the HPM version.

**Comment by Andenfighter** [comment]
yeah, after un- and reinstalling the mod it's fixed. apparently i had two folders in my mods, dod and divergences of darkness, so it was probably due to 2 versions of the mod conflicting with each other. sorry for the trouble

**Comment by Capitanloco6** [comment]
No problem, enjoy!
