### ISSUE TITLE
Permission of localization

### ISSUE THREAD

**Issue by shudorcl** [Pergame35/Divergences#140]
Dear devs, We are fans of DoD from China.We have completely translated your marvelous work into Chinese though you haven't permitted us to do that before, so we are now making a request to gain the permission as we have already accomplished localization.
Now we are translating the latest DoD version on Github. Since we found that the current version has introduced a lot of HPM texts, compared to the official version, would you keep the current text files in the current way or integrate them into several new files in the official version?
We will be grateful if you agree to grant permission for our localization generously and your answer for our question above will be quite helpful for our following arrangement.

**Comment by Capitanloco6** [comment]
Hello, this sounds like a great idea! I would be honored. Personally, I find it would be easier to keep the current file structure for localisation.

Cheers and good luck.
