### ISSUE TITLE
Can’t conquer India

### ISSUE THREAD

**Issue by TrogIodyte** [Pergame35/Divergences#145]
I am unable to fabricate conquest cases belli on Indian minors, regardless of size or civilizational progress. In the early game, I saw one war for Indian provinces. Afterwards, I noticed Indian AND the indonesian minors remained untouched by other European powers (I am playing Yugoslavia.) it is now 1869, on the eve of African colonization and very few wars have been fought at all by Europeans (except against other Europeans) and it is impossible to make clothes due to the EXTREMELY limited amount of dye.

**Comment by Lys0gen** [comment]
> regardless of size

I doubt that. Since a couple versions conquering non-african uncivs with more than 0.5/1/2/3/4 million pops requires you to have increasingly higher military and naval techs.

See /common/cb_types.txt for details if you know how to read the files.

**Comment by TrogIodyte** [comment]
Thanks for your reply, this makes some sense. However, my game was already far advanced, I believe the year was 1875. No wars had been fought in India by this point, with the majority of greater powers already having completed the second line of naval and army techs. I'm assuming this is not intentional, and that India could be conquered much sooner than 1880?

**Comment by Lys0gen** [comment]
Did Spain stay a GP?
If they fall from GP status the "Treaty of Selon" is abolished which gives all european AI great/secondary powers free CBs on India & Indonesia. They usually carve it up pretty quickly then.

**Comment by TrogIodyte** [comment]
HEYyyyyy! That would be it. Thank you so much!
