### ISSUE TITLE
(Bug) Forced Scandinavia to release and puppet Scotland, it also puppeted Spain

### ISSUE THREAD

**Issue by TovarFriedman** [Pergame35/Divergences#153]
Spain was in my sphere but not part of the war.

**Comment by TovarFriedman** [comment]
Wait, it actually puppetted my entire sphere.

**Comment by Capitanloco6** [comment]
This should be fixed in the hotfix branch, find it here: https://github.com/Capitanloco6/Divergences-HPM/tree/Divergences-HPM-Hotfixes

Otherwise, in the next few weeks I'll also push a new patch here that will include the fix for the Release as Puppet CB.
