### ISSUE TITLE
Gran colombia poor decision and events diversity

### ISSUE THREAD

**Issue by NekMC** [Pergame35/Divergences#36]
Great colombia is very dry in decisions and history after unifying the republics there is not much to do more than buying islands, I propose to fill it with more events and decisions like ameriga federetion or arcadia

**Comment by NekMC** [comment]
sorry for my ugly english i am a hispanic dud xDD

**Comment by Pergame35** [comment]
Yeah sure, that's great but is it a general thought or do you have more precise ideas ?

**Comment by NekMC** [comment]
yeah like an event about the conquest of the incas,event to improve life ratings of important cities, a type of manifest destiny for gran colombia to unify arcadia and ameriga,decisions to buy islands in the pacific like rapa nui or hawaii, something to improve the assimilation of the incas,decision to do rail ways from nova lusitania[texas] to andagoyan territories as the transcontinental railroad in us history, and more decision of build universities in andagoya,lusitania etc. to dont be an overpower nation some invented revolutions for example indepence of lusitania. salvadorian troubles, granadians loyalist to the spanish crown. thank you for listen me i wish that my ideas can be of usefullness :)
