### ISSUE TITLE
'We have assumed control over suez canal' event crashing game

### ISSUE THREAD

**Issue by jam67** [Pergame35/Divergences#50]
For some reason the event for taking control of the Suez is firing despite me having never lost control of it, and without any interaction crashes the game a second or two after loading said event.

Save game linked which should have the issue occur within 2-3 months in game.
https://drive.google.com/file/d/1abi-CKOt_PcqCTw0MZhWNast4KBmPVYX/view?usp=sharing

**Comment by Hibari-chan** [comment]
I think when the HPM was merged with the mod they choose the wrong files to not replace.
The DoD canal Decisions are different in the PDM version i wonder if just copying them over will fix it. or if that causes other issues. Will try for my next game

**Comment by Hibari-chan** [comment]
I have a fix for your save file and the Canal Decisions in general
Open mod/divergences of darkness/common/event_modifies file
and copy and past this into your file. 
"#### Kiel Canal ####
building_kiel_canal = {
	icon = 9
}

kiel_canal = {
	prestige = 0.03
	icon = 15
}

kiel_canal_dividend = {
	icon = 9
}
#### Panama Canal ####
building_panama_canal = {
	prestige = 0.03
	icon = 9
}

panama_canal = {
	prestige = 0.05
	icon = 15
}

panama_canal_dividend = {
	icon = 9
}

panama_canal_treaty = {
	icon = 5
}

panama_canal_treaty_annuity = {
	icon = 9
}

building_panama_canal_scandal = {
	icon = 10
}
#### Suez Canal ####
building_suez_canal = {
	prestige = 0.03
	icon = 9
}

building_suez_canal_revolt = {
	icon = 16
}

suez_canal = {
	prestige = 0.05
	icon = 15
}

suez_canal_dividend = {
	icon = 9
}

suez_canal_treaty = {
	icon = 5
}

suez_canal_treaty_annuity = {
	icon = 9
}
"

**Comment by jam67** [comment]
Thanks for the fast response the event now fires without issue and so I can continue my game, cheers.
