### ISSUE TITLE
Clicking on island causes crash

### ISSUE THREAD

**Issue by ckanbak** [Pergame35/Divergences#58]
Clicking on one of the islands north of Tahiti and south of Hawaii(I think Kiribati, but I'm not sure), causes the game to crash.

**Comment by mad-marx** [comment]
I think I found a fix for that one, Kirimati isn't assigned to any region/state in the regions.txt file. You can fix it by just adding the province id (3249) to one of the regions by entering it into one of the brackets for whatever state you want the province to belong to. I picked the Tahiti region, so FRA_1097.
