### ISSUE TITLE
Game breaking 1 line in Clean_Up

### ISSUE THREAD

**Issue by Zealotx10** [Pergame35/Divergences#62]
The "ai = no" line 259 in Clean_Up.txt decision file prevents all the AI countries in the game from ever getting the "existing_country" flag, which in turn prevents them from discovering a ton of inventions, including the important colonization ones. Probably a bunch of other issues stemming from this as well

**Comment by kyle-simon** [comment]
This looks like it was just a poorly copied over decision from HPM. That block you're referencing is supposed to be enclosed in the OR block, so that the AI can set the flags on the player.

**Comment by kyle-simon** [comment]
[https://github.com/arkhometha/Historical-Project-Mod/blob/master/HPM/decisions/CleanUp.txt](url)
