### ISSUE TITLE
Crash when hovering over select decision button with Japan

### ISSUE THREAD

**Issue by RuiCardona** [Pergame35/Divergences#74]
My country became a presidential dictatorship and I got the option to enable the secret police. The problem is that whenever I got to select that decision (hover over the button) the game freezes and crashes.

**Comment by Sinkpooper** [comment]
Seems to be a problem for all dictatorships, in addition the AI dictatorships enact this decision every day

**Comment by Capitanloco6** [comment]
Fixed a few versions ago, thanks for reporting!
