### ISSUE TITLE
Issue with launching the mod

### ISSUE THREAD

**Issue by elerionpm** [Pergame35/Divergences#81]
Hello, I have a problem with launching the mod. Whenever the loading screen gets to "creating rivers" the game crashes.

**Comment by Sesnii** [comment]
Had this issue myself and asked around online and found a solution that seems to work:

delete the map cache folder in your victoria 2 folders both in the steam & documents folders. in addition to the ones shown in the screenshot I also deleted the cache folder from the documents/paradox interactive/victoria 2/DoD/map folder.

![image](https://user-images.githubusercontent.com/65820538/91470088-42993f80-e862-11ea-8d33-43d9ba3f0a90.png)
