### ISSUE TITLE
Inca Westernisation event doesn't remove unciv westernisation modifiers

### ISSUE THREAD

**Issue by JustHerby** [Pergame35/Divergences#89]
When you get event ID 66898 as Tawantinsuyu, "The Inauguration of Pachacuti II", the country westernises but you don't lose any of the country modifiers like western influences etc, and the militancy from those really adds up towards the end of the game. I've added the code from the westernisation decision that removes the modifiers, see attached, seems to work fine.

[IncaModernization - 66900.txt](https://github.com/Pergame35/Divergences/files/5079183/IncaModernization.-.66900.txt)

**Comment by Capitanloco6** [comment]
Fixed, thanks for insight!
