### ISSUE TITLE
Justifying War crashes game

### ISSUE THREAD

**Issue by xxxSmoker** [Pergame35/Divergences#97]
I just downloaded the new version and decided to play Bengal. When I clicked the justify CB button on Taungu the game showed the CB selection screen and crashed. I tried on another country and it did the same thing. I'm guessing it has something to do with the new CB restrictions. Hope this gets fixed.

**Comment by Capitanloco6** [comment]
Thanks, reverted it for now until I have more time to analise what's wrong with it
